apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-entsoe-exporter.fullname" . }}
  labels:
    {{- include "jarvis-entsoe-exporter.labels" . | nindent 4 }}
data:
  bq-enable: {{ .Values.config.bqEnable | quote }}
  bq-init: {{ .Values.config.bqInit | quote }}
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}
  state-enable: {{ .Values.config.stateEnable | quote }}