apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarvis-entsoe-exporter.fullname" . }}
  labels:
    {{- include "jarvis-entsoe-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  keyfile.json: {{ .Values.secret.gcpServiceAccountKeyfile | toString | b64enc }}
  entsoe-api-key: {{ .Values.secret.entsoeApiKey | toString | b64enc }}